### ISSUE TITLE
No colors in gnome-terminal

### ISSUE THREAD

**Issue by mogenson** [kooparse/hodl-ticker#5]
![hodl](https://user-images.githubusercontent.com/900731/49298974-a4a9f280-f48c-11e8-95a9-b24b1feb9092.png)

```
$ gnome-terminal --version
# GNOME Terminal 3.30.2 using VTE 0.54.2 +GNUTLS
```

Works fine in XTerm.

**Comment by kooparse** [comment]
Hi @mogenson!

I am pretty sure it comes from the [term](https://github.com/Stebalien/term) library. 
I will try to look at this soon!

**Comment by mogenson** [comment]
Thanks for the tip about where to look.

See here: https://github.com/kooparse/hodl-ticker/pull/6
