### ISSUE TITLE
doesn't seem to be able to build with the rust 2018. termion doesn't compile

### ISSUE THREAD

**Issue by kuatroka** [kooparse/hodl-ticker#7]
![rust_error](https://user-images.githubusercontent.com/9093546/50652870-bbf26900-0f7f-11e9-9692-640426cdca69.PNG)

**Comment by kooparse** [comment]
Thanks for the report @kuatroka. I will update this repo to the 2018 edition ;)

**Comment by kooparse** [comment]
@kuatroka Arf, in fact `termion` doesn't support the windows platform.
