### ISSUE TITLE
Doesn't work anymore ('cause coinmarketcap is private)

### ISSUE THREAD

**Issue by kooparse** [kooparse/hodl-ticker#9]
The public API from coinmarketcap is private now. So this CLI doesn't work anymore. I'll see what exists (for replacing coinmarketcap) in the coming days.

**Comment by tmlee** [comment]
How about giving the CoinGecko API a try? https://www.coingecko.com/en/api
It is public, free and open. Should be an easy implementation. I am here to help answer any questions as well!

**Comment by kooparse** [comment]
@tmlee Done! Thanks again for your API, this project is using it now! ;)
